name: trucker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  avatar_glow:
    git:
      url: https://github.com/apgapg/avatar_glow
      ref: master
  b_dep:
    git:
      url: https://blupDependenent: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@github.com/BlupGithub/b_dep.git
      ref: v1.1241


  cupertino_icons: ^1.0.2
  country_code_picker:
  telephony: ^0.2.0
  otp_text_field: ^1.1.3
  pinput: ^3.0.1
  flutter_svg: ^2.0.7
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  firebase_auth: ^4.7.1
  cloud_firestore: ^4.8.3
  fluttertoast: ^8.2.4
  firebase_database: ^10.2.4
  google_sign_in: ^6.1.4
  google_nav_bar: ^5.0.6
  geocoder2: ^1.4.0
  geolocator: ^10.0.1
  intl_phone_field: ^3.2.0
  flutter_textfield_validation: ^0.0.2
  contacts_service: ^0.6.3
  permission_handler: ^10.2.0
  flutter_screenutil: ^5.6.0
  google_place: ^0.4.7
  google_maps_flutter: any
  flutter_polyline_points: any
  sms_autofill: ^2.3.0
  shared_preferences: ^2.2.1
  get: ^4.6.6
  extended_phone_number_input: ^1.0.2
  url_launcher: ^6.1.9
  flutter_phone_direct_caller: ^2.1.1
  awesome_ripple_animation: ^2.0.0
  share_plus: ^7.2.1
  uuid: ^3.0.7
  dio: ^4.0.6
  speech_to_text: ^6.3.0
  image_picker: ^1.0.4
  flutter_staggered_grid_view: ^0.7.0
  camerax: ^0.1.1
  intl: ^0.18.1
  flutter_sensors: ^1.0.1
  flutter_compass: ^0.8.0
  collection: ^1.15.0
  vibration: ^1.8.4
  geocoding: ^2.1.1
  crisp_chat: ^0.0.4
  flutter_stripe: ^10.0.0
  flutter_local_notifications: ^16.2.0
  flutter_background_service: ^5.0.5
  http: ^1.1.0
  toggle_switch: ^2.1.0
  html: ^0.15.4
  flutter_native_splash: ^2.3.9

dependency_overrides:
  http: ^1.1.0
  flutter_polyline_points: any
  flutter_screenutil: 5.0.2
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.3.8

flutter_native_splash:
  color: "#fffff"
  image: assets/image/splash_.png

flutter_icons:
  image_path:"assets/image/truckerLink.png"
  ios:true
#  adaptive_icon_foreground: "assets/image/logolink.png"




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/image/
    - assets/maptheme/darktheme.json
    - assets/maptheme/lightheme.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
